### ISSUE TITLE
Not working in Julia 1.0

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGraphics/Winston.jl#293]
I tried Winston again given that @tknopp informed us that is was ready for Julia 1.0:
https://discourse.julialang.org/t/plotting-packages-that-support-julia-v1-0/14125/33

I tried running the following simple example with Winston from Julia 1.0, with no success:
```
using Winston
x=collect(-10:10)
plot(x, x.^3)
> Error showing value of type FramedPlot:
> ERROR: UndefVarError: showall not defined
```
***NOTE:*** I get the same issue if I move to the most recent version of Winston on the `master` branch.

I admit, it does work from Julia 0.7, though.  However, I have found that even after porting to Julia 0.7, there will still be a few small issues that need fixed by debugging your package in Julia 1.0 directly (the missing `showall` function in 1.0, for example).

### `test` directory
I also tried running some of the code from the test directory (`runtests.jl`).  Overall, this runs relatively well in 0.7 (though there appears to be a few snags).  Sadly, I cannot get the test code to run at all on Julia 1.0.

Again, I think this is one of those cases where the code must be updated/debugged using Julia 1.0 itself.  The execution seems to get caught on silly little things like @sprintf having been moved (`@sprintf` must now be imported from the `Printf` module (`import Printf: @sprintf`))

**Comment by tknopp** [comment]
ok, the `showall` was simple. For me the test pass on 1.0

**Comment by tknopp** [comment]
@ma-laforge: could you be more specific what you tested regarding the `@sprintf` issue? In runtests.jl we have `using Printf`. Or did you execute individual test files (instead of runtests.jl)?

**Comment by tknopp** [comment]
tests are passing: https://travis-ci.org/JuliaGraphics/Winston.jl/builds/430611531
Despite the tests not running on Linux / 0.7

**Comment by tknopp** [comment]
@ma-laforge please reopen, if I missed something

**Comment by tknopp** [comment]
don't worry. Now everything is working and that is what counts. Thanks a lot for the bug report!
