### ISSUE TITLE
1.0.0 ERROR: UndefVarError: showall not defined , on 0.7 working

### ISSUE THREAD

**Issue by programistawpf** [JuliaGraphics/Winston.jl#294]
| | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.0 (2018-08-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Winston

julia> plot(rand(10))
Error showing value of type FramedPlot:
ERROR: UndefVarError: showall not defined

On 0.7 working....
Paul

**Comment by tknopp** [comment]
thanks, I fixed this 3 hours ago, see https://github.com/JuliaGraphics/Winston.jl/issues/293

A new release is already tagged and just needs to be merged:
https://github.com/JuliaLang/METADATA.jl/pull/18143

Until that you can checkout master (add Winston#master in Pkg mode)
