### ISSUE TITLE
timeplot example code fails

### ISSUE THREAD

**Issue by WurdahMekanik** [JuliaGraphics/Winston.jl#297]
The [example code for timeplot](https://winston.readthedocs.io/en/latest/fun/timeplot.html) fails with this error

`ERROR: MethodError: no method matching datetime2unix(::Array{DateTime,1})`

**Comment by cmey** [comment]
I fixed this here https://github.com/JuliaGraphics/Winston.jl/pull/307
@WurdahMekanik If this is fixed for you now, can you close this?

**Comment by cmey** [comment]
@tknopp I believe we can close this issue.

**Comment by tknopp** [comment]
thanks
