### ISSUE TITLE
Please update to support Cairo 0.7

### ISSUE THREAD

**Issue by Ales999** [JuliaGraphics/Winston.jl#301]
Cairo 0.7 fixed  build for mac os

**Comment by tknopp** [comment]
This is not fixable until Gtk uses Binary Builder. https://github.com/JuliaPackaging/Yggdrasil/issues/62

I am also waiting for that. @ianshmean @giordano and @staticfloat are working on that.

**Comment by Ales999** [comment]
Thanks for the quick response. Well, we'll wait.
