### ISSUE TITLE
Winston messes with bigint 

### ISSUE THREAD

**Issue by my-little-repository** [JuliaGraphics/Winston.jl#311]
The following weird  behavior appears with julia 1.7.1 and Winston v0.15.2

  julia> big(1//2)
    1//2
    
    julia> using Winston
    Gtk-Message: 14:17:40.676: Failed to load module "canberra-gtk-module"
    Gtk-Message: 14:17:40.677: Failed to load module "canberra-gtk-module"
    
    julia> big(1//2)
    0//0

**Comment by tknopp** [comment]
Probably because `Winston.jl` was developed against something like Julia v0.2? So its really just because of Julia having changed quite strongly.
